version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
    volumes:
      - .:/app
    extra_hosts:
      - "example.org:127.0.0.1"
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5673:5672"
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A task.celery worker --loglevel=info
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit